uploads = []
outputs = []

[[generated]]
id = "07kxzjfeFsh_UhfrTWHK0"
uri = "file://artifacts/pop-the-question/public/logo-cutout.png"
type = "image"
title = "Transparent Pop logo cutout"

[[generated]]
id = "twYYmw6ZCthkAXZ036Ciy"
uri = "file://artifacts/pop-the-question-mobile/assets/images/icon.png"
type = "image"
title = "app icon"

[[generated]]
id = "v81uU1JEiH1gpxfo6arVG"
uri = "file://artifacts/pop-the-question-mobile/assets/images/splash.png"
type = "image"
title = "splash screen"
